modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Sleep%20Sooner"
iconFile="icon.png"

[[mods]]
modId="sleepsooner"
version="5.1"
displayName="Sleep Sooner"
displayURL="https://serilum.com/mod/sleep-sooner"
authors="Serilum"
description='''A minimalistic mod that adds a configurable functionality to be able to sleep a little sooner.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.sleepsooner]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sleepsooner]]
    modId="minecraft"
    type="required"
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "sleepsooner.mixins.json"